default: &default
adapter: redis
url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: smiggles_production
